### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by mrhappyma** [macedonga/lofi.twitch.auto.stream#1]
Stream is down

RIP 24/7 lo-fi

**Comment by macedonga** [comment]
What doesn't work?

**Comment by hamadottv** [comment]
it doesnt work to 24/7 stream, fix this plz

**Comment by macedonga** [comment]
> it doesnt work to 24/7 stream, fix this plz

What exactly doesn't work? I tried it on twitch and on youtube and it works just fine

**Comment by hamadottv** [comment]
@macedonga can you tell me what to do later?
